<template>
  <div>
    <Toolbar class="fixed w-screen bottom-0">
      <template #start>
        <Button as="router-link" label="Router" to="/" id="game-home-button">Home</Button>
      </template>
      <template #center>
        <p>COMBO: {{ combo }}</p>
      </template>
      <template #end>
        <Button @click="toggleHelpButton">Help</Button>
      </template>
    </Toolbar>
    <!-- eslint-disable vue/no-v-model-argument -->
    <Dialog v-model:visible="helpButton" modal class="w-4/6">
      <p class="text-2xl">Help / Instructions</p>
      <br />
      <p>
        Of the two pieces of art shown, one was drawn by an actual artist and one was generated by
        AI. Please pick the piece of art that you think is AI generated. After you've made your
        choice, click Submit and we'll tell you if you were correct or incorrect.
      </p>
      <br />
      <p>You can double click an image to zoom in and take a closer look.</p>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import Toolbar from 'primevue/toolbar'
import Dialog from 'primevue/dialog'
import Button from 'primevue/button'
import { ref } from 'vue'

const combo = ref(0)
const helpButton = ref(false)

function toggleHelpButton() {
  helpButton.value = !helpButton.value
}
</script>

<style scoped></style>
