<template>
  <div>
    <Toolbar class="fixed w-screen bottom-0">
      <template #start>
        <Button as="RouterLink" label="Router" to="/" id="game-home-button">Home</Button>
      </template>
      <template #center>
        <p>COMBO: {{ artStore.combo }}</p>
      </template>
      <template #end>
        <Button @click="helpButton = !helpButton">Instructions</Button>
      </template>
    </Toolbar>
    <!-- eslint-disable vue/no-v-model-argument -->
    <Dialog v-model:visible="helpButton" header="Instructions / How to play" class="w-4/5" modal>
      <div>
        <div v-for="instruction in gameInstructions" :key="instruction">
          <h2 class="font-bold">{{ instruction.header }}</h2>
          <p v-for="inst in instruction.text" :key="inst">{{ inst }}</p>
          <br />
        </div>
      </div>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import Toolbar from 'primevue/toolbar'
import Dialog from 'primevue/dialog'
import Button from 'primevue/button'
import { ref } from 'vue'
import { useArtStore } from '../../stores/art'

const artStore = useArtStore()
const helpButton = ref(false)

const gameInstructions = [
  {
    header: 'Overview',
    text: [
      'In this game, you’ll be shown two images side by side. Your task is to identify which one was generated by AI.'
    ]
  },
  {
    header: 'How to play',
    text: [
      '1. Look closely at both images displayed on the screen.',
      '2. Click on the image you believe was generated by AI',
      '3. Once you make your selection, the game will reveal whether your choice was correct'
    ]
  },
  {
    header: 'COMBO',
    text: ["The 'COMBO' number indicates your streak. See how many you can get right in a row!"]
  }
]
</script>

<style scoped></style>
