<template>
  <div v-for="instruction in instructions" :key="instruction">
    <h2 class="font-bold">{{ instruction.header }}</h2>
    <p v-for="inst in instruction.text" :key="inst">{{ inst }}</p>
    <br />
  </div>
</template>

<script setup>
const instructions = [
  {
    header: 'Overview',
    text: [
      'In this game, you’ll be shown two images side by side. Your task is to identify which one was generated by AI.'
    ]
  },
  {
    header: 'How to play',
    text: [
      '1. Look closely at both images displayed on the screen.',
      '2. Click on the image you believe was generated by AI',
      '3. Once you make your selection, the game will reveal whether your choice was correct'
    ]
  },
  {
    header: 'COMBO',
    text: ["The 'COMBO' number indicates your streak. See how many you can get right in a row!"]
  }
]
</script>

<style scoped></style>
