<template>
    <div>
        <h2 class="font-bold">Overview</h2>
        <p>In this game, you’ll be shown two images side by side. Your task is to identify which one was generated by AI.</p>
        <br>
        <h2 class="font-bold">How to play</h2>
        <p>1. Look closely at both images displayed on the screen.</p>
        <p>2. Click on the image you believe was generated by AI.</p>
        <p>3. Once you make your selection, the game will reveal whether your choice was correct.</p>
        <br>
        <p>The "COMBO" number indicates your streak. See how many you can get right in a row!</p>
    </div>
</template>

<script setup lang="ts">

</script>

<style scoped>

</style>